import { airOperationsText } from './air-operations.mjs';
import { uiModel } from './ui-model.mjs';
import { convoyCoverage } from './task-forces.mjs';
import { PROFILES, NATION_ORDER } from './catalog.mjs';
import { PORTS, MAP_CAPITALS } from './world.mjs';
import { POWERS, navalInfluence } from './land-war.mjs';
import { portPopup } from './inspection-view.mjs';
import { contactDescription } from './contact-alerts.mjs';
import { fleetPosition, fleetStatus, fleetMissionBlock, MISSIONS } from './task-forces.mjs';
import { capitalClock } from './campaign-clock.mjs';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Math.round(v||0).toLocaleString('en-US');
const button=(label,action,attrs='')=>`<button data-action="${action}" ${attrs}>${label}</button>`;
const rows=items=>`<dl class="command-details">${items.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;
const heading=(label,title)=>`<span class="eyebrow">${label}</span><h2>${esc(title)}</h2>`;
const information=(label,title,summary,body,notes='')=>`<div class="map-information"><section class="selection-summary">${heading(label,title)}${summary}</section><section class="selection-data">${body}</section><section class="selection-notes">${notes}</section></div>`;
const coordinates=p=>`${Math.abs(p[1]).toFixed(1)}°${p[1]<0?'S':'N'} ${Math.abs(p[0]).toFixed(1)}°${p[0]<0?'W':'E'}`;

export function commandSelection(s,c,ui,data,{fleet,stats,supply,contact,convoy,composition,manifest}){
 const n=s.nations[s.player],territory=data.features?.find(t=>t.id===ui.territoryId),country=ui.countryId||(territory&&(s.world?.control[territory.id]||territory.owner)),front=s.world?.fronts.find(f=>f.id===ui.frontId);
 if(ui.credits)return information('WORLD CHART','Powers & map credits',button('Reset to world view','map-reset','title="Reset map rotation and zoom."'),`<div class="chart-powers">${Object.entries(POWERS).map(([id,p])=>`<span style="color:${p.color}">${esc(p.name)}</span>`).join('')}</div><p>Equal Earth projection. Approximate ${data.date?.slice(0,4)||1936} game boundaries built from <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth public-domain map data</a>. Historical ownership and interwar corrections are authored game overlays.</p>`,`<p>Drag to pan. Scroll or use + / − to zoom; Home resets. Select chart items to inspect them in the right panel.</p><p>Friendly movement animates at up to 60 fps, limited by the display refresh rate. Combat and scouting still process every simulated minute. Enemy markers stay at reported positions. Crowded friendly symbols use leader lines to mark their actual locations; zoom in to separate them.</p>`);
 if(ui.portId&&PORTS[ui.portId]){const {summary,body,notes}=portPopup(s,c,ui.portId,{parts:true});return information('PORT & COAST DEFENSE',PORTS[ui.portId].name,summary,body,notes);}
 if(front)return information('LAND FRONT',front.name,`<p>${esc(front.status)}</p><div class="front-progress"><i style="width:${front.progress*100}%;background:${POWERS[front.attacker]?.color}"></i></div>`,rows([['Belligerents',`${PROFILES[front.attacker]?.name||front.attacker} / ${PROFILES[front.defender]?.name||front.defender}`],['Attacker progress',num(front.progress*100)+'%'],['Attacker / defender supply',num(front.attackerSupply*100)+'% / '+num(front.defenderSupply*100)+'%'],['Naval influence',navalInfluence(front)]]),'<p>Sustained supply advantages can change the outcome. Islands and overseas armies depend more on naval supply than continental interiors.</p>');
 if(country){const relation=s.relations[[s.player,country].sort().join('-')],color=POWERS[country]?.color||'#9aa5b0';return information(territory?'TERRITORY':'CAPITAL & GOVERNMENT',territory?.name||MAP_CAPITALS[country]?.name||POWERS[country]?.name||country,`<p style="color:${color}">${esc(POWERS[country]?.name||territory?.name||country)}</p>`,rows([['Administration',territory&&s.world?.control[territory.id]?'Occupied territory':'National territory'],['Relations with your ministry',country===s.player?'Your government':relation?`${relation.war?'At war':relation.allied?'Allied':'At peace'} · ${Math.round(relation.score)}`:'Outside the seven playable powers']]),(NATION_ORDER.includes(country)&&country!==s.player?button('Government relations','view','data-view="diplomacy" title="Open diplomatic actions and current treaty policy."'):'')+'<p>Only observed naval contacts are shown on the chart.</p>');}
 if(contact)return information('INTELLIGENCE CONTACT',PROFILES[contact.nation].name,`<p>${esc(contact.stage)} · ${num(contact.confidence*100)}% confidence</p>`,`<p>${esc(contactDescription(s,contact))}</p>`,'<p>Only wartime contacts create alerts; they expire after 48 hours without an update. Last-known positions fade on the map for up to seven days.</p>');
 if(convoy){const t=capitalClock(s,s.player,convoy.arriveAt),coverage=uiModel(s)?.escortCoverage||convoyCoverage(s,c),cover=coverage.convoys.find(v=>v.id===convoy.id); return information('MERCHANT SHIPPING',convoy.name,'',rows([['Merchant hulls',num(convoy.count)],...(convoy.aviationTransfer?(()=>{const t=n.airTransfers.find(t=>t.id===convoy.aviationTransfer);return [['Aircraft cargo',num(t?.airWing.reduce((v,w)=>v+w.count,0))],['Aviation supplies',num(t?.supplies)+' sortie units']];})():[]),['Escort coverage',cover?.defense>0?'Escorted':'Exposed'],['Protecting forces',cover?.escorts.map(id=>coverage.escorts.find(e=>e.id===id)?.name).join(', ')||'None within 148 km'],['Escort defense',num(cover?.defense)],['Nearest escort',cover?.nearestKm!=null?num(cover.nearestKm)+' km':'None at sea'],['Position',coordinates(fleetPosition(s,convoy))],['Speed',convoy.speed+' kn'],['Next arrival',t.date+' '+t.time]]),'<p>These ships belong to your merchant register. Operational escorts within 148 km can intervene against raiders. Defense includes training, morale and supply; coverage does not guarantee safety.</p>');}
 if(!fleet)return '';
 const mission=ui.mission||fleet.mission,aggressive=ui.aggressiveBattle??fleet.aggressiveBattle??false,block=fleetMissionBlock(s,c,s.player,fleet,mission);
 const overview=heading(fleet.role==='support'?'AUTOMATIC SUPPORT':'FLEET ORDERS',fleet.name)+`<p class="fleet-composition">${composition}</p><p class="fleet-status">${esc(fleetStatus(s,fleet))}</p><p class="panel-note">${esc(airOperationsText(s,c,s.player,fleet))}</p><div class="fleet-readiness">${[['Training',n.training],['Morale',n.morale],['Supply',supply.factor*100]].map(([label,value])=>`<div><span>${label}</span><b>${num(value)}%</b></div>`).join('')}</div>`;
 const orders=fleet.role==='support'?'<p>Admiral-managed '+(fleet.supportKind==='depot'?'depot deployment. Fully staffed ships add capacity at their actual friendly port.':'replenishment route. Oilers meet fleets, transfer stores and return to reload.')+'</p>'+rows([['Assignment',fleet.supportTarget?esc(n.fleets.find(f=>f.id===fleet.supportTarget)?.name||'Reassessing'):PORTS[fleet.supportDestination||fleet.port]?.name||'Awaiting deployment'],['Cargo remaining',fleet.supportKind==='oiler'?num(fleet.supportCargo)+' supply units':'Workshop and depot services']])+'<p>Vulnerable at sea and at anchor; spare escorts accompany support when available.</p>':['repair','reinforcement'].includes(fleet.role)?'<p>This detachment is traveling to a friendly port and remains vulnerable to interception.</p>':`<label for="fleet-mission">Mission</label><select id="fleet-mission" title="Choose a strategic mission. Admirals determine operating areas, routes and targets.">${Object.entries(MISSIONS).map(([id,m])=>`<option value="${id}" ${id===mission?'selected':''}>${m.name}</option>`).join('')}</select><p class="mission-description">${MISSIONS[mission].description}</p><label class="check-label risk-check" title="Accept unfavorable odds and press attacks longer. More damage inflicted, greater risk of losses."><input id="aggressive-battle" type="checkbox" ${aggressive?'checked':''}> Seek aggressive battle</label>${button('Transmit fleet orders','fleet-order',`data-id="${fleet.id}" class="primary full" ${block?`disabled title="${esc(block)}"`:``}`)}${fleet.needsEscorts?'<small class="block-reason">Holding for an adequate escort screen.</small>':''}`;
 return `<div class="command-fleet-layout"><section class="fleet-overview">${overview}</section><section class="fleet-mission-controls">${orders}</section><section class="selected-manifest" aria-label="Assigned ships and operational details">${manifest}</section></div>`;
}
