import { DESIGN_ROLES, evaluateDesign } from './designer.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Math.round(v||0).toLocaleString('en-US');
export function designerView(s,recipe){
  if(!recipe)return '';
  const n=s.nations[s.player];let r,error='';try{r=evaluateDesign(recipe,s.player);}catch(e){error=e.message;}
  const limits=r?.limits;
  const fields=[['tons','Standard displacement · t',100,90000,100],['caliber','Main gun caliber · mm',0,508,1],['guns','Main gun barrels',0,16,1],['torpedoes','Torpedo tubes',0,24,1],['armor','Belt armor · mm',0,450,5],['speed','Maximum speed · knots',12,40,.5],['range','Endurance · km',1852,29632,1],['aircraft','Aircraft capacity',0,120,1]];
  const block=error||(!r.valid?'The fit exceeds available displacement.':'')||(n.gold<r.fee?'Insufficient gold for the drafting fee.':'');
  return '<section class="panel ship-designer"><div class="panel-title"><div><span class="eyebrow">'+recipe.year+' DESIGN BUREAU</span><h2>New class draft</h2></div><button data-action="close-designer" class="subtle">Close designer</button></div><p>Apply suggested fit replaces these fields using the selected role, current year, your national catalog and the missions assigned to ships of this type. Previewing is free; gold is charged only when you register the design. Hulls are ordered separately.</p><div class="draft-top"><label>Class name<input data-draft="name" maxlength="70" value="'+esc(recipe.name)+'"></label><label>Ship role<select data-draft="role">'+Object.entries(DESIGN_ROLES).map(([id,label])=>'<option value="'+id+'" '+(id===recipe.role?'selected':'')+'>'+label+'</option>').join('')+'</select></label><button data-action="generate-draft" title="Replaces the draft name and specifications for the selected role with a period-appropriate suggestion. No resources spent.">Apply suggested fit</button></div><div class="draft-fields">'+fields.map(([key,label,min,max,step])=>'<label>'+label+'<input type="number" data-draft="'+key+'" min="'+min+'" max="'+max+'" step="'+step+'" value="'+(key==='range'?Math.round(recipe[key]*1.852):recipe[key])+'"></label>').join('')+'</div>'+(limits?'<p class="panel-note">Current role limits: '+num(limits.minTons)+'–'+num(limits.maxTons)+' t · '+limits.maxCaliber+' mm guns · '+limits.maxSpeed+' knots · '+limits.maxAir+' aircraft.</p>':'')+(r?'<div class="draft-weights">'+Object.entries(r.weights).map(([key,v])=>'<span title="'+key+': '+num(v)+' t" style="flex-grow:'+v+'">'+key+'</span>').join('')+'</div><div class="draft-quote"><span class="'+(r.free<0?'negative':'')+'"><b>'+num(r.free)+'</b> t displacement margin</span><span><b>'+num(r.gold)+'</b> base hull gold · '+num(n.gold)+' available</span><span><b>'+num(r.industry)+'</b> base hull industry · '+num(n.industry)+' available</span><span><b>'+num(r.fee)+'</b> gold drafting fee</span></div>':'')+'<p class="panel-note">Standardization discounts apply when ordering the hull. Your treaty policy can restrict construction. These are provisional engineering and cost estimates.</p>'+(block?'<p class="block-reason">'+esc(block)+'</p>':'')+'<button data-action="commission-draft" class="primary" '+(block?'disabled title="'+esc(block)+'"':'')+'>Pay drafting fee & register design</button></section>';
}
