import { monthlyIncome } from './engine.mjs';
import { merchantEconomy } from './merchant-economy.mjs';
import { warBalances } from './war-balance.mjs';
import { PROFILES, NATION_ORDER } from './catalog.mjs';
const num=(v,d=0)=>v.toLocaleString('en-US',{maximumFractionDigits:d});
export function warView(s,compact=false){const wars=warBalances(s);if(!wars.length)return '';return `<div class="${compact?'war-strip':'war-overview'}" aria-label="Active wars">${wars.map(w=>`<div class="war-estimate ${w.result.toLowerCase()}" title="Estimated balance: sunk tonnage + 35% of damage-equivalent tonnage + 15% of merchant GRT, plus land campaign progress. Not a victory condition."><span>WAR · <b style="color:${PROFILES[w.opponent].color}">${w.name}</b></span><strong>${w.winner?PROFILES[w.winner].name+' leading':'Even so far'}</strong>${compact?'':`<small>Your side / opponent: ${num(w.own.sunk)} / ${num(w.enemy.sunk)} t sunk; ${num(w.own.damage)} / ${num(w.enemy.damage)} t damage-equivalent inflicted · Land balance ${num(w.land)}</small>`}</div>`).join('')}</div>`;}
export function economyView(s,c){return budgetView(s,c)+`<section class="panel economy-panel"><h2>Domestic economy & maritime trade</h2><p>Gold is a monthly government appropriation. Naval industry produces daily. Trade supports the maritime share of gold, industry and influence; the domestic share remains available when trade is cut. Shipyard throughput depends on industry expansion, funding and paid operating costs.</p><table><thead><tr><th>Nation</th><th>Domestic / trade</th><th>Available / required capacity</th><th>Shipping coverage</th><th>Port trade capacity</th><th>Income factor</th><th>Logistics</th></tr></thead><tbody>${NATION_ORDER.map(id=>{const e=merchantEconomy(s,c,id);return `<tr><td style="color:${PROFILES[id].color}">${PROFILES[id].name}</td><td>${num(e.domestic*100)} / ${num(e.trade*100)}%</td><td>${num(e.current)} / ${num(e.required)} GRT${e.estimated?' *':''}</td><td>${num(e.coverage*100)}%</td><td>${num(e.ports.available)} / ${num(e.ports.baseline)} points · ${num(e.ports.coverage*100)}%</td><td>${num(e.economyFactor*100)}%</td><td>${num(e.logistics)}%</td></tr>`;}).join('')}</tbody></table><p class="panel-note">Every completed naval-industry expansion adds 15% of opening merchant capacity to shipping demand. New merchants restore capacity when delivered; extra capacity is a reserve against losses. GRT measures registered volume, not naval displacement or cargo weight. Trade flow = merchant coverage × convoy flow × port trade access. Port access is surviving, unblocked port trade points divided by opening national points, capped at 100%. Occupation removes access to lost ports. Domestic income remains independent. Ratios and demand are provisional balance values.${s.campaignId==='campaign_1922'?' * Soviet shipping is a provisional 100 hulls / 100,000 GRT.':''}</p></section>`;}

function budgetView(s,c){
 const income=monthlyIncome(s,c),signed=v=>(v>=0?'+':'−')+num(Math.abs(v)),n=s.nations[s.player];
 return '<section class="panel budget-panel"><div class="panel-title"><h2>Your operating budget</h2><button data-action="view" data-view="programs" title="Change funding and expand facilities.">Adjust funding</button></div><div class="budget-balances"><span class="'+(income.netGold<0?'negative':'positive')+'"><b>'+signed(income.netGold)+'</b> gold / month</span><span class="'+(income.netIndustry<0?'negative':'positive')+'"><b>'+signed(income.netIndustry)+'</b> industry / month</span></div><table><thead><tr><th>Scheduled flow · monthly equivalent</th><th>Gold</th><th>Industry</th></tr></thead><tbody><tr><td>Appropriation after upkeep & treaty policy</td><td>'+signed(income.gold)+'</td><td>—</td></tr><tr><td>Naval industry output</td><td>—</td><td>'+signed(income.industry)+'</td></tr>'+income.facilities.rows.map(r=>'<tr><td>'+r.label+' operations</td><td>−'+num(r.gold/12)+'</td><td>−'+num(r.industry/12)+'</td></tr>').join('')+'</tbody></table><p class="panel-note">Planned balance at current funding and selected aircraft models. Government gold arrives each month; operating costs and industry output occur daily. Ship orders, research, diplomacy and repairs are additional. Shortages reduce output. Aircraft production adds about '+num(income.facilities.aircrewDemand)+' aircrew positions per year; aviation schools fund '+num(n.aviatorsYear*n.aviatorFunding)+' graduates per year, arriving quarterly.</p></section>';
}
