import { trainingDescription } from './personnel-training.mjs';
import { uiModel } from './ui-model.mjs';
import { capitalClock } from './campaign-clock.mjs';
import { SPEEDS, aircraftSummary } from './naval-resources.mjs';
import { monthlyIncome, fleetPower, yardLoad } from './engine.mjs';
import { sailorSummary } from './ship-staffing.mjs';
import { merchantEconomy } from './merchant-economy.mjs';
import { warBalances } from './war-balance.mjs';
import { musicStatus } from './music.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=0)=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:d});
const compact=v=>Math.abs(v)>=1e9?num(v/1e9,1)+'bn':Math.abs(v)>=1e6?num(v/1e6,1)+'m':Math.abs(v)>=1e4?num(v/1e3,1)+'k':num(v);
const balance=v=>(v>=0?'+':'−')+compact(Math.abs(v));
const signed=v=>(v>=0?'+':'−')+num(Math.abs(v)),pct=v=>num(v*100)+'%';
export function topBars(s,c,m={}){
 const n=s.nations[s.player],clock=capitalClock(s),v=uiModel(s),air=v?.air||aircraftSummary(s,c),crew=v?.crew||sailorSummary(s,c),e=v?.economy||merchantEconomy(s,c),income=v?.income||monthlyIncome(s,c),wars=warBalances(s);
 const stats=[
 ['GOLD',compact(n.gold),num(n.gold)+' gold · '+signed(income.netGold)+' / month planned balance after upkeep and all facility funding; excludes new orders and repairs. Appropriations arrive monthly; facilities spend daily.'],['INFLUENCE',num(n.influence),signed(income.influence)+' / month'],['INDUSTRY',compact(n.industry),num(n.industry)+' industry · '+signed(income.netIndustry)+' / month planned balance after aircraft and school use; excludes new orders and repairs. Gross production '+num(income.industry)+' / month.'],
 ['TRADE',pct(e.tradeFlow),'Realized trade: merchant coverage × convoy flow × usable port trade capacity'],['HOME / TRADE',num(e.domestic*100)+' / '+num(e.trade*100)+'%', 'Domestic / trade income shares'],['SHIPPING',num(e.current/1e6,1)+'/'+num(e.required/1e6,1)+'m',num(e.current)+' / '+num(e.required)+' GRT available / required · '+pct(e.coverage)+' coverage'],
 ['PORT TRADE',num(e.ports.available)+' / '+num(e.ports.baseline),'Usable / opening port trade points · '+pct(e.ports.coverage)+' access; damage and blockades reduce it'],['LOGISTICS',num(e.logistics)+'%','Effective logistics; fleet supply also depends on nearest port distance, damage and capacity'],['SUPPLY',pct((v?.power||fleetPower(s,c)).supply),'Hull-weighted fleet supply'],['TRAINING',num(n.training)+'%','National training'],['MORALE',num(n.morale)+'%','National morale'],['YARDS',compact((v?.yards||yardLoad(s,c)).capacity*365),num((v?.yards||yardLoad(s,c)).capacity*365)+' tons per year after funding and port damage'],
 ['SAILORS ±',balance(crew.balance),num(crew.total)+' trained / '+num(crew.required)+' required · '+crew.waiting+' ships waiting for complete crews · '+trainingDescription(s,n,'sailors'),crew.balance<0],['AVIATORS ±',balance(air.aviatorBalance),num(n.aviators)+' aviators / '+num(air.aviatorsRequired)+' required across every aircraft · '+trainingDescription(s,n,'aviators'),air.aviatorBalance<0],['AIRCRAFT',compact(air.total),num(air.total)+' aircraft · '+num(air.assigned)+' embarked · '+num(air.stationed)+' ashore · '+num(air.transit)+' in transit · '+num(air.reserve)+' reserve · '+num(air.uncrewed)+' without complete aircrews']
 ];
 const speed=s.paused?'PAUSED':m.warming?'Measuring…':num(m.actual)+'× actual';
 return `<header class="command-bar time-bar"><strong class="campaign-clock">${clock.date} <b>${clock.time}</b> <small>${clock.capital} · ${clock.zone}</small></strong><div class="clock-controls"><span class="actual-speed ${s.paused?'is-paused ':''}${s.paused||m.warming?'':m.ratio<.65?'slow-red':m.ratio<.9?'slow-yellow':''}" title="Measured simulation speed. Slows safely under load; no game minutes are skipped.">${speed}</span>${s.paused?'<button data-action="step-minute" title="Advance one minute">+1m</button><button data-action="step-hour" title="Advance one hour">+1h</button>':''}<button data-action="pause" class="pause-control">${s.paused?'▶ Resume':'Ⅱ Pause'}</button><select id="speed" aria-label="Simulation speed">${SPEEDS.map(([v,t])=>`<option value="${v}" ${s.speed===v?'selected':''}>${t}</option>`).join('')}</select><label class="check-label auto-pause-control" title="Pause for mandatory decisions; resume after they are resolved. Manual pause stays paused."><input id="auto-pause" type="checkbox" ${s.autoPause?'checked':''}>Auto-pause</label></div><div class="header-audio"><label title="Sound effects"><input id="sound-enabled" type="checkbox" ${s.audioEnabled?'checked':''}>SFX</label><input id="sound-volume" aria-label="Sound effects volume" type="range" min="0" max="100" value="${s.audioVolume*100}"><label title="Music"><input id="music-enabled" type="checkbox" ${s.musicEnabled?'checked':''}>Music</label><input id="music-volume" aria-label="Music volume" type="range" min="0" max="100" value="${s.musicVolume*100}"><button data-action="music-next" title="Next track · now ${esc(musicStatus().track.title)}" aria-label="Next music track">▶|</button></div></header><div class="resources resource-bar" style="--resource-count:${stats.length+(wars.length?2:0)}" aria-label="National resources">${stats.map(([label,value,hint,negative])=>`<div class="${negative?'negative':''}" data-resource="${esc(label)}" tabindex="0" aria-label="${esc(label+': '+hint)}"><label>${label}</label><strong>${value}</strong></div>`).join('')}${wars.length?`<div class="resource-war" title="${esc(wars.map(w=>w.name+': '+w.result+' · war balance '+num(w.score)+' = naval '+num(w.naval)+' + land '+num(w.land)+'. Naval balance values sunk tonnage + 35% damaged tonnage + 15% merchant GRT. Leading/trailing compares losses and land progress; it does not predict victory.').join(' · '))}"><label>AT WAR · BALANCE</label><strong>${wars.map(w=>w.opponent+' '+(w.result==='Leading'?'↑':w.result==='Trailing'?'↓':'↔')).join(' · ')}</strong></div>`:''}</div>`;
}
