import { COMBAT_RULES as R } from './rules.mjs';

// Selected historical rosters; engineering numbers below are rounded scenario
// assumptions. Outcomes are generated by the engine and never forced to history.
const ship = (id, name, type, tons, speed, caliber, barrels, belt, deck, extras = {}) =>
  ({ classId: `demo-${id}`, name, type, tons, speed, caliber, barrels, belt, deck, aa: 20, ...extras });
const carrier = (id, name, tons, speed, fighters, strikes) => ship(id, name, 'CV', tons, speed, 127, 8, 76, 32,
  { aircraft: { fighter: fighters, strike: strikes }, aa: 45 });
const PRESET_SHIPS = {
  'denmark-strait': {
    A: [ship('hood1941', 'HMS Hood', 'BC', 42000, 30, 381, 8, 305, 76),
      ship('prince-of-wales', 'HMS Prince of Wales', 'BB', 35000, 28, 356, 10, 350, 130, { crewQuality: .85, radar: true })],
    B: [ship('bismarck', 'Bismarck', 'BB', 42000, 30, 380, 8, 320, 100, { radar: true }),
      ship('prinz-eugen', 'Prinz Eugen', 'CA', 14500, 32, 203, 8, 80, 30, { tubes: 12, torpedoRange: 8 })],
  },
  midway: {
    A: [carrier('enterprise', 'USS Enterprise', 20000, 32, 27, 48), carrier('hornet', 'USS Hornet', 20000, 32, 27, 48), carrier('yorktown', 'USS Yorktown', 20000, 32, 25, 45)],
    B: [carrier('akagi1942', 'Akagi', 37000, 31, 21, 54), carrier('kaga1942', 'Kaga', 38000, 28, 21, 54), carrier('soryu', 'Soryu', 16000, 34, 21, 42), carrier('hiryu', 'Hiryu', 17500, 34, 21, 42)],
  },
  'north-cape': {
    A: [ship('duke-of-york', 'HMS Duke of York', 'BB', 35000, 28, 356, 10, 350, 130, { radar: true }),
      ship('belfast', 'HMS Belfast', 'CL', 11500, 32, 152, 12, 114, 51, { radar: true, tubes: 6, torpedoRange: 9 }),
      ship('norfolk', 'HMS Norfolk', 'CA', 10000, 31, 203, 8, 76, 38, { radar: true, tubes: 8, torpedoRange: 9 })],
    B: [ship('scharnhorst', 'Scharnhorst', 'BC', 32000, 31, 283, 9, 350, 95, { radar: false, tubes: 6, torpedoRange: 8 })],
  },
};
export const SCENARIOS = Object.freeze([
  { id: 'denmark-strait', title: 'Denmark Strait', date: '24 May 1941', sideA: 'Royal Navy', sideB: 'Kriegsmarine', separationKm: 23,
    environment: { visibilityKm: 28, seaState: 3, night: false },
    description: 'Hood and Prince of Wales meet Bismarck and Prinz Eugen.',
    approximation: 'Four principal ships with rounded engineering values. Initial positions and ship AI are scenario assumptions; historical losses are not scripted.',
    sourceUrl: 'https://www.royalnavy.mod.uk/news/2021/may/24/20210524-loss-hood' },
  { id: 'midway', title: 'Midway', date: '4 June 1942', sideA: 'U.S. Navy', sideB: 'Imperial Japanese Navy', separationKm: 220,
    environment: { visibilityKm: 35, seaState: 2, night: false },
    description: 'Three American carriers face four Japanese carriers through grouped air strikes.',
    approximation: 'Carrier-only encounter; escorts, land-based aircraft, scouting uncertainty and the later submarine attack are omitted. Air groups and starting separation are rounded scenario assumptions.',
    sourceUrl: 'https://www.history.navy.mil/browse-by-topic/wars-conflicts-and-operations/world-war-ii/1942/midway.html' },
  { id: 'north-cape', title: 'North Cape', date: '26 December 1943', sideA: 'Royal Navy', sideB: 'Kriegsmarine', separationKm: 18,
    environment: { visibilityKm: 12, seaState: 6, night: true },
    description: 'Duke of York, Belfast and Norfolk engage Scharnhorst in an Arctic night.',
    approximation: 'Selected four-ship encounter, omitting the wider destroyer and convoy forces. Radar and weather affect combat; the historical sinking is not guaranteed.',
    sourceUrl: 'https://cd.royalnavy.mod.uk/-/media/rnweb/locations-and-operations/navy-historical-branch/pdfs/1943/war_diary_naval_1943_12---day-16-to-day-31.pdf?rev=a4112afdf50c4c2f8953a60e7dd2eece' },
]);
function rowsToShips(content, rows, side) {
  if (!Array.isArray(rows)) throw Error('Choose the ships for each side.');
  const ships = [];
  for (const [rowIndex, row] of rows.entries()) {
    const cl = content.classes?.[row.classId];
    if (!cl) throw Error(`Unknown ship class: ${row.classId}`);
    const count = Number(row.count);
    if (!Number.isInteger(count) || count < 1 || count > 120 || ships.length + count > 120) throw Error('Choose 1–120 hulls per fleet.');
    for (let hullIndex = 0; hullIndex < count; hullIndex++) {
      const capacity = cl.air || 0, groupId = `custom-${rowIndex}`;
      ships.push({ ...cl, id: `${side}:${groupId}:${hullIndex}`, groupId, hullIndex, initialCount: count,
        classId: row.classId, name: `${cl.name}${count > 1 ? ` ${hullIndex + 1}` : ''}`, health: 1,
        aircraft: { fighter: Math.round(capacity * (1 - R.air.strikeFraction)), strike: Math.floor(capacity * R.air.strikeFraction) } });
    }
  }
  if (!ships.length) throw Error('Each side needs at least one ship.');
  return ships;
}
export function buildCustomScenario(content, options = {}) {
  return { seed: options.seed ?? 1, separationKm: options.separationKm ?? 24, maxDurationSeconds: options.maxDurationSeconds,
    environment: options.environment, metadata: { id: 'custom', title: 'Custom engagement', accuracy: 'Game simulation with catalog ship characteristics; generic carrier air-group mix.' },
    sides: Object.fromEntries(['A', 'B'].map(side => [side, { name: options[`name${side}`] || `Fleet ${side}`,
      doctrine: options[`doctrine${side}`] || 'balanced', formation: options[`formation${side}`] || 'line-ahead',
      ships: rowsToShips(content, options[`ships${side}`], side) }])) };
}
export function buildScenario(content, options = {}) {
  const preset = SCENARIOS.find(s => s.id === (options.presetId || 'denmark-strait'));
  if (!preset) throw Error('Unknown historical scenario.');
  return { seed: options.seed ?? 1, separationKm: options.separationKm ?? preset.separationKm,
    maxDurationSeconds: options.maxDurationSeconds ?? (preset.id === 'midway' ? 14400 : 7200),
    environment: { ...preset.environment, ...options.environment }, metadata: { ...preset },
    sides: Object.fromEntries(['A', 'B'].map(side => [side, { name: preset[`side${side}`],
      doctrine: options[`doctrine${side}`] || 'balanced', formation: options[`formation${side}`] || 'line-ahead',
      ships: PRESET_SHIPS[preset.id][side].map((s, i) => ({ ...s, aircraft: { ...s.aircraft }, id: `${side}:preset-${i}:0`, groupId: `preset-${i}`, hullIndex: 0, initialCount: 1 })) }])) };
}
